app:
  name: "marketplace-dev"
  env: "dev"
  version: "1.0.0"

http:
  port: 8080

logger:
  # zap config level
  level: "info"
  prod: false

firebase_storage:
  bucket_name: "contents-dev.phygital"
