app:
  name: "common"
  # values: localhost, staging, production
  env: "localhost"
  version: "0.0.1"

http:
  port: "8080"

logger:
  # zap config level
  level: "debug"
  rollbar_env: "go-clean-template"

mongo:
  db_name: "phygital-dev"
  conn_uri: "mongodb://root:password@localhost:27017"

firebase_storage:
  bucket_name: "contents-dev.phygital"
